num_observations: 66
params:
  seed: ${...seed}

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: masa_actor_critic
    actions_num_list: [2, 2, 2, 2]
    # leg0_inds: [0,1,2,3,13,14,15,25,29,33,37,38,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65]
    # leg1_inds: [0,4,5,6,16,17,18,26,30,34,37,39,43,44,45,42,47,48,49,46,51,52,53,50,55,56,57,54,59,60,61,58,63,64,65,62]
    # leg2_inds: [0,7,8,9,19,20,21,27,31,35,37,40,44,45,42,43,48,49,46,47,52,53,50,51,56,57,54,55,60,61,58,59,64,65,62,63]
    # leg3_inds: [0,10,11,12,22,23,24,28,32,36,37,41,45,42,43,44,49,46,47,48,53,50,51,52,57,54,55,56,61,58,59,60,65,62,63,64]
    shared_agents_inds: [[0,1,2,3,13,14,15,25,29,33,37,38,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65],
                          [0,4,5,6,16,17,18,26,30,34,37,39,43,44,45,42,47,48,49,46,51,52,53,50,55,56,57,54,59,60,61,58,63,64,65,62],
                          [0,7,8,9,19,20,21,27,31,35,37,40,44,45,42,43,48,49,46,47,52,53,50,51,56,57,54,55,60,61,58,59,64,65,62,63],
                          [0,10,11,12,22,23,24,28,32,36,37,41,45,42,43,44,49,46,47,48,53,50,51,52,57,54,55,56,61,58,59,60,65,62,63,64]]
    input_shape: 36
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256, 128, 64]
      activation: elu
      d2rl: False
      
      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: ${if:${...checkpoint},True,False} # flag which sets whether to load the checkpoint
  load_path: ${...checkpoint} # path to the checkpoint to load

  config:
    name: ${resolve_default:Ant,${....experiment}}
    full_experiment_name: ${.name}
    env_name: rlgpu
    device: ${....rl_device}
    device_name: ${....rl_device}
    multi_gpu: False
    ppo: True
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 0.01
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 3e-4
    lr_schedule: adaptive
    schedule_type: legacy
    kl_threshold: 0.008
    score_to_win: 20000
    max_epochs: ${resolve_default:500,${....max_iterations}}
    save_best_after: 100
    save_frequency: 50
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 16
    minibatch_size: 32768
    mini_epochs: 4
    critic_coef: 2
    clip_value: True
    seq_len: 4
    bounds_loss_coef: 0.0001
