num_observations: [4, 60]
params:
  seed: ${...seed}

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: masa_actor_critic
    actions_num_list: [2, 2, 2, 2]
    inds_neg: [41,42,49,50,57,58]
    shared_agents_inds: [[0, 1, 2, 3, 4, 5, 15, 16, 17, 27, 31, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 72, 73, 74, 84, 85, 86, 96, 97, 98, 108, 109, 110, 120, 121, 122, 132, 133, 134, 144, 145, 146],
                          [0, 1, 2, 6, 7, 8, 18, 19, 20, 28, 32, 35, 37, 38, 39, 36, 41, 42, 43, 40, 45, 46, 47, 44, 49, 50, 51, 48, 53, 54, 55, 52, 57, 58, 59, 56, 63, 64, 65, 75, 76, 77, 87, 88, 89, 99, 100, 101, 111, 112, 113, 123, 124, 125, 135, 136, 137, 147, 148, 149],
                          [0, 1, 2, 9, 10, 11, 21, 22, 23, 29, 33, 35, 38, 39, 36, 37, 42, 43, 40, 41, 46, 47, 44, 45, 50, 51, 48, 49, 54, 55, 52, 53, 58, 59, 56, 57, 66, 67, 68, 78, 79, 80, 90, 91, 92, 102, 103, 104, 114, 115, 116, 126, 127, 128, 138, 139, 140, 150, 151, 152],
                          [0, 1, 2, 12, 13, 14, 24, 25, 26, 30, 34, 35, 39, 36, 37, 38, 43, 40, 41, 42, 47, 44, 45, 46, 51, 48, 49, 50, 55, 52, 53, 54, 59, 56, 57, 58, 69, 70, 71, 81, 82, 83, 93, 94, 95, 105, 106, 107, 117, 118, 119, 129, 130, 131, 141, 142, 143, 153, 154, 155]]
    input_shape: 60
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256, 128, 64]
      activation: elu
      d2rl: False
      
      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: ${if:${...checkpoint},True,False} # flag which sets whether to load the checkpoint
  load_path: ${...checkpoint} # path to the checkpoint to load

  config:
    name: ${resolve_default:Ant,${....experiment}}
    full_experiment_name: ${.name}
    env_name: rlgpu
    device: ${....rl_device}
    device_name: ${....rl_device}
    multi_gpu: False
    ppo: True
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 0.01
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 3e-4
    lr_schedule: adaptive
    schedule_type: legacy
    kl_threshold: 0.008
    score_to_win: 20000
    max_epochs: ${resolve_default:500,${....max_iterations}}
    save_best_after: 100
    save_frequency: 50
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 16
    minibatch_size: 32768
    mini_epochs: 4
    critic_coef: 2
    clip_value: True
    seq_len: 4
    bounds_loss_coef: 0.0001
