num_observations: [2, 75]
params:
  seed: ${...seed}

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: masa_actor_critic
    actions_num_list: [12, 12]
    inds_neg: [32, 53, 74]
    left_inds: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,16,17,14,15,18,20,19,24,25,26,21,22,23,28,27,31,32,29,30,33,34,37,38,35,36,39,41,40,45,46,47,42,43,44,49,48,52,53,50,51,54,55,58,59,56,57,60,62,61,66,67,68,63,64,65,70,69,73,74,71,72]
    left_inds_neg: [2,4,6,7,9,11,12,18,33,39,54,60]
    left_act_inds_neg: [0,4,11]
    input_shape: 75
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [400, 200, 100]
      activation: elu
      d2rl: False
      
      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: ${if:${...checkpoint},True,False} # flag which sets whether to load the checkpoint
  load_path: ${...checkpoint} # path to the checkpoint to load

  config:
    name: ${resolve_default:Humanoid,${....experiment}}
    full_experiment_name: ${.name}
    env_name: rlgpu
    device: ${....rl_device}
    device_name: ${....rl_device}
    multi_gpu: False
    ppo: True
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 0.01
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 5e-4
    lr_schedule: adaptive
    kl_threshold: 0.008
    score_to_win: 20000
    max_epochs: ${resolve_default:1000,${....max_iterations}}
    save_best_after: 100
    save_frequency: 100
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 32
    minibatch_size: 32768
    mini_epochs: 5
    critic_coef: 4
    clip_value: True
    seq_len: 4
    bounds_loss_coef: 0.0001
